// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_grpc.proto

// Protobuf Java Version: 3.25.5
package Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC;

public final class HelloGrpc {
  private HelloGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.MyNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 value = 1;</code>
     * @return The value.
     */
    int getValue();
  }
  /**
   * Protobuf type {@code Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.MyNumber}
   */
  public static final class MyNumber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.MyNumber)
      MyNumberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyNumber.newBuilder() to construct.
    private MyNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyNumber() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyNumber();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.internal_static_Lecture_07_gRPC_Source_Code_lec_07_prg_01_hello_gRPC_MyNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.internal_static_Lecture_07_gRPC_Source_Code_lec_07_prg_01_hello_gRPC_MyNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber.class, Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_ = 0;
    /**
     * <code>int32 value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public int getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0) {
        output.writeInt32(1, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber)) {
        return super.equals(obj);
      }
      Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber other = (Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber) obj;

      if (getValue()
          != other.getValue()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.MyNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.MyNumber)
        Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.internal_static_Lecture_07_gRPC_Source_Code_lec_07_prg_01_hello_gRPC_MyNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.internal_static_Lecture_07_gRPC_Source_Code_lec_07_prg_01_hello_gRPC_MyNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber.class, Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber.Builder.class);
      }

      // Construct using Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        value_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.internal_static_Lecture_07_gRPC_Source_Code_lec_07_prg_01_hello_gRPC_MyNumber_descriptor;
      }

      @java.lang.Override
      public Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber getDefaultInstanceForType() {
        return Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber.getDefaultInstance();
      }

      @java.lang.Override
      public Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber build() {
        Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber buildPartial() {
        Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber result = new Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.value_ = value_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber) {
          return mergeFrom((Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber other) {
        if (other == Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber.getDefaultInstance()) return this;
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                value_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int value_ ;
      /**
       * <code>int32 value = 1;</code>
       * @return The value.
       */
      @java.lang.Override
      public int getValue() {
        return value_;
      }
      /**
       * <code>int32 value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(int value) {

        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.MyNumber)
    }

    // @@protoc_insertion_point(class_scope:Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.MyNumber)
    private static final Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber();
    }

    public static Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyNumber>
        PARSER = new com.google.protobuf.AbstractParser<MyNumber>() {
      @java.lang.Override
      public MyNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MyNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Lecture_07_gRPC_Source_Code.lec_07_prg_01_hello_gRPC.HelloGrpc.MyNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lecture_07_gRPC_Source_Code_lec_07_prg_01_hello_gRPC_MyNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lecture_07_gRPC_Source_Code_lec_07_prg_01_hello_gRPC_MyNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020hello_grpc.proto\0224Lecture_07_gRPC_Sour" +
      "ce_Code.lec_07_prg_01_hello_gRPC\"\031\n\010MyNu" +
      "mber\022\r\n\005value\030\001 \001(\0052\234\001\n\tMyService\022\216\001\n\nMy" +
      "Function\022>.Lecture_07_gRPC_Source_Code.l" +
      "ec_07_prg_01_hello_gRPC.MyNumber\032>.Lectu" +
      "re_07_gRPC_Source_Code.lec_07_prg_01_hel" +
      "lo_gRPC.MyNumber\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Lecture_07_gRPC_Source_Code_lec_07_prg_01_hello_gRPC_MyNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Lecture_07_gRPC_Source_Code_lec_07_prg_01_hello_gRPC_MyNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lecture_07_gRPC_Source_Code_lec_07_prg_01_hello_gRPC_MyNumber_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
